### ISSUE TITLE
Remove form from user profile

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-web#35]
As part of #33, we won't need to have a user profile form that allows the user to submit values. The user information is now read-only, coming from the Hub.

So we can replace the form and use normal HTML elements such as `<p>`.

**Comment by kinow** [comment]
New screen will look like:

![image](https://user-images.githubusercontent.com/304786/53309276-dc99c800-390b-11e9-94f4-48672294ab45.png)

**Comment by kinow** [comment]
We could maybe in the future include some text somewhere explaining that the information is provided by the Hub. But not sure whether we will actually have any information about the Hub in the UI. And if so, also not sure how we should call it. Cylc Hub? Hub? JupyterHub?

**Comment by hjoliver** [comment]
> 
> 
> We could maybe in the future include some text somewhere explaining that the information is provided by the Hub. But not sure whether we will actually have any information about the Hub in the UI. And if so, also not sure how we should call it. Cylc Hub? Hub? JupyterHub?

Cylc Hub!

**Comment by hjoliver** [comment]
(But credit JupyterHub in the small print).

**Comment by kinow** [comment]
Any suggestion for what it should say? Right now it is only saying read-only view from your data...

And can we really call it Cylc Hub? I like it, but if someone packaged Cylc in some solution and renamed it, I would have some mixed feelings about it :S

**Comment by kinow** [comment]
Although with credit too... that should be Ok? Happy to update the text... but am really horrible taking decisions about colour, names, font size, etc hahaha
