### ISSUE TITLE
Produce development version to work with cylc-jupyterhub

### ISSUE THREAD

**Issue by kinow** [cylc/cylc-web#36]
Now `cylc-jupyterhub` supports pointing to any directory with an `index.html` to serve as the Web GUI for the Cylc UI Server.

It would be good to have a better way to code `cylc-web` and see the results with and without the Hub. Preferably something quick, as generating production files takes some 20 seconds that could be better spent doing something else.

**Comment by kinow** [comment]
Current overview of modules in the application.

![image](https://user-images.githubusercontent.com/304786/53386582-b9dce180-39e7-11e9-9f7b-c2a2a39b0ab8.png)

Also adding the task to produce this report.

**Comment by kinow** [comment]
One alternative would be running the WebPack Proxy https://vuejs-templates.github.io/webpack/proxy.html, which is normally used to send the requests back to a running instance of the backend.

The issue is that we have Tornado handling authentication, cookie handling, and loading a static `index.html`. :thinking:

**Comment by kinow** [comment]
This option might work: https://github.com/vuejs/vue-cli/issues/1317

If we are able to produce an `index.html` with the `watch` feature, that would be a good development setup IMO.

**Comment by kinow** [comment]
Well, apparently that works. Takes about 2 seconds, and produces a development version of `index.html`. Whew. Thought would have to dig into webpack, vue, and start trying to work on it from scratch :-) :heart: OpenSource

**Comment by hjoliver** [comment]
Sounds cool, might get you to explain this to me to tomorrow!

**Comment by kinow** [comment]
Sure thing! I'm hoping to have written a unit test, and then the #33 issue will be pretty much done (finally!)
